### ISSUE TITLE
No inventory data for Czechia (CZE) so inventory total for CW_EU isn't plot

### ISSUE THREAD

**Issue by aliceramsden** [openghg/fluxie#10]
I'll update the inventory files with the data for CZE, if this is available.

**Comment by aliceramsden** [comment]
I've updated the inventory files on the ICOS Jupyter Hub, but when solving this issue I've found another bug:

The 3 letter definition string for CW_EU contains 'SVK-SVK' at the end, when it should be 'SVK-SVN' (line 45 in PARIS_inversion_results.py). However, this error is also included in InTEM's processed filenames, so we'd need to fix out files internally before fixing that line the notebook, otherwise the plotting fails and it can't find that region name.

I'll make a note to fix this internally then push a fix for the notebook after that.

**Comment by mo-aliceramsden** [comment]
This has been fixed in InTEM's files and in the notebook, with a work-around when inventory values are missing for aggregated regions.
